### ISSUE TITLE
Rending Gale Crash

### ISSUE THREAD

**Issue by Crazy-KSK** [P3pp3rF1y/Reliquary#137] opened 2016-07-20 00:13 UTC
I was just flying around with it for about 10 minutes when the game randomly crashed 
http://pastebin.com/uahe4Yr3

Edit: ah looks like it happens when spamming right click while flying around http://pastebin.com/SruyvnMM

**Comment by P3pp3rF1y** [comment] 2016-07-20 13:11
I guess this is not single player, but on dedicated server.

This is related to how capability data syncs today, basically the more you click the more they will try to sync and more likely it is that the code in question will get into inconsistent state. 

I have a pull request MinecraftForge/MinecraftForge#3099 for this that should change the way the synchronization is done and will fix this issue.

**Comment by Crazy-KSK** [comment] 2016-07-21 04:04
No, this actually happens in an "offline" game

**Comment by adrwa** [comment] 2016-07-29 09:43
@Crazy-KSK in a singleplayer word, minecraft still has two things running, client, and server, no matter how you're playing it will always sync between the two just sometimes its locally.

**Comment by P3pp3rF1y** [comment] 2016-07-29 11:16
Well, that's true, but this specific issue is caused by two different packets being synced at the same time where one tries to display value and the other overrides the value with empty collection. 
When in single player this seems to be way less likely based on observation of values displayed, that's why I asked about multiplayer vs single player

**Comment by P3pp3rF1y** [comment] 2016-09-13 10:41
In the latest release there is a change that should hopefully limit these to absolute minimum, so I am going to close this, please create a new issue in case you another one of these.

**Closed as completed by P3pp3rF1y** 2016-09-13 10:41 UTC
