### ISSUE TITLE
[1.16.4] Crash with Mmm

### ISSUE THREAD

**Issue by GeekJokes** [P3pp3rF1y/Reliquary#494] opened 2021-01-03 22:09 UTC
### I got a crash twice when shooting at a dummy form Mmm with an ender bullet - first time i shot directly at it and got this crash:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 03/01/21 03:23
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity$DummyMob.func_70097_a(TargetDummyEntity.java:363) ~[?:1.0.0] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.doDamage(ShotEntityBase.java:322) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.onImpact(EnderShotEntity.java:61) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.func_70227_a(EnderShotEntity.java:53) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.func_70071_h_(ShotEntityBase.java:227) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.world.ClientWorld$$Lambda$9601/440568899.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1451516720.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity$DummyMob.func_70097_a(TargetDummyEntity.java:363) ~[?:1.0.0] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.doDamage(ShotEntityBase.java:322) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.onImpact(EnderShotEntity.java:61) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.func_70227_a(EnderShotEntity.java:53) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.func_70071_h_(ShotEntityBase.java:227) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.world.ClientWorld$$Lambda$9601/440568899.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: xreliquary:ender_shot (xreliquary.entities.shot.EnderShotEntity)
	Entity ID: 32686
	Entity Name: entity.xreliquary.ender_shot
	Entity's Exact location: 6.52, 57.11, -1.11
	Entity's Block location: World: (6,57,-2), Chunk: (at 6,3,14 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.12, -0.08, -1.18
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['GeekJokes'/64, l='ClientLevel', x=5.90, y=56.00, z=3.60]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,55,8), Chunk: (at 8,3,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 408324 game time, 418324 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1451516720.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

### then i reopened the game and shot another bullet, now pointed at a wall, and got this other crash:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 03/01/21 03:27
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity$DummyMob.func_70097_a(TargetDummyEntity.java:363) ~[?:1.0.0] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.doDamage(ShotEntityBase.java:322) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.onImpact(EnderShotEntity.java:61) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.func_70227_a(EnderShotEntity.java:53) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.func_70071_h_(ShotEntityBase.java:227) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.world.ClientWorld$$Lambda$9612/1225337237.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1963590892.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity$DummyMob.func_70097_a(TargetDummyEntity.java:363) ~[?:1.0.0] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.doDamage(ShotEntityBase.java:322) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.onImpact(EnderShotEntity.java:61) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.EnderShotEntity.func_70227_a(EnderShotEntity.java:53) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at xreliquary.entities.shot.ShotEntityBase.func_70071_h_(ShotEntityBase.java:227) ~[?:1.16.3-1.3.4.1061] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.world.ClientWorld$$Lambda$9612/1225337237.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: xreliquary:ender_shot (xreliquary.entities.shot.EnderShotEntity)
	Entity ID: 32481
	Entity Name: entity.xreliquary.ender_shot
	Entity's Exact location: 6.61, 57.10, -1.39
	Entity's Block location: World: (6,57,-2), Chunk: (at 6,3,14 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.04, -0.03, -0.40
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['GeekJokes'/67, l='ClientLevel', x=6.89, y=56.00, z=2.48]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,55,8), Chunk: (at 8,3,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 408896 game time, 418896 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1963590892.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

**Comment by P3pp3rF1y** [comment] 2021-01-04 01:18
The issue is Mmm relying on player passed in damage source being nonullable when it can be nullable. They need to be prepared for that. I can try passing the player that shot the bullet in there, but not sure if it's always going to be possible and it's definitely not going to fix any other that may properly decide to pass in null.

https://github.com/MehVahdJukaar/DuMmmMmmy1.16/blob/master/src/main/java/net/mehvahdjukaar/dummmmmmy/entity/TargetDummyEntity.java#L363

**Comment by P3pp3rF1y** [comment] 2021-04-04 22:38
In dev I have a version that reuses what vanilla does in terms of tracking player who fired them for arrows/trident/... once that is released I will close this issue. Any additional similar NPEs will need to be investigated on mmm side.

**Comment by P3pp3rF1y** [comment] 2021-04-11 08:57
this is now fixed in the latest release on curseforge

**Closed as completed by P3pp3rF1y** 2021-04-11 08:57 UTC
Labels: fixed in development
