### ISSUE TITLE
Question regarding ender staff

### ISSUE THREAD

**Issue by KamiSami** [P3pp3rF1y/Reliquary#422] opened 2020-04-26 00:10 UTC
I've been trying to right click like mad and it also has absorbed ender pearls, but it wont do teleportation or long teleportations at all, is this bugged or am i being stupid on how this works?

**Comment by P3pp3rF1y** [comment] 2020-04-26 19:50
Simple right click once charged will throw an enderpearl like projectile that will teleport you. Just make sure that you are not set to wraith node mode as that only teleports you to the wraith node that the ender staff is set to.

Let me know if you have any issues with that and if so I will need more info like version, if there are other mods in the pack etc. Otherwise I will close this in a few days.

**Comment by KamiSami** [comment] 2020-04-26 21:16
These are the mods i am using, so reliquary's version is in there, the forge version is forge-31.1.48

    AppleSkin-mc1.15.2-forge-1.0.13.jar
    AttributeFix-1.15.2-7.0.2.jar
    BetterAdvancements-1.15.2-0.1.0.96.jar
    Botania r1.15-382.jar
    classicbar-3.0.2.jar
    Clumps-5.0.2.jar
    CreativeCore_v2.0.5_mc1.15.2.jar
    curios-FORGE-1.15.2-2.0.2.2.jar
    Cyclic-1.15.2-0.3.4.jar
    DungeonCrawl-1.15.2-1.6.3.jar
    EnhancedVisuals_v1.3.12_mc1.15.2.jar
    EnigmaticLegacy-1.7.0.jar
    flexible_skills-1.15.2-1.2.1-beta.jar
    Hwyla-forge-1.10.8-B72_1.15.2.jar
    industrial-foregoing-1.15.2-2.2.2-28d4a81.jar
    jei-1.15.2-6.0.0.3.jar
    journeymap-1.15.2-5.7.0beta1.jar
    mahoutsukai-1.15.2-v1.15.17.jar
    Mekanism-1.15.2-9.10.1.414.jar
    MouseTweaks-2.13-mc1.15.1.jar
    NetherPortalFix_1.15.2-6.0.0.jar
    NomadicTents-1.15.2-11.0.0-beta.jar
    noRecipeBook_v1.5.2formc1.15.2.jar
    Patchouli-1.15.2-1.2-31.jar
    prefab-1.5.0.4.jar
    ProjectE-1.15.2-PE1.0.3B.jar
    QuantumStorage-1.15.2-5.1.1.jar
    Reliquary-1.15.2-1.3.4.984.jar
    swingthroughgrass-1.15.2-1.4.0.jar
    themidnight-0.5.7-2.jar
    titanium-1.15.2-2.3.7.jar
    tombstone-4.3.5-1.15.2.jar
    useful_backpacks-1.15.2-1.9.4.63.jar
    u_team_core-1.15.2-2.11.0.156.jar
    Vampirism-1.15.2-1.6.0-alpha+20200421-1031.jar
    Waystones_1.15.2-6.0.1.jar

And also the logs for client is spamming quite a lot of this:

[27huhtikuuta2020 00:13:42.817] [Render thread/ERROR] [net.minecraft.client.MainWindow/]: ########## GL ERROR ##########
[27huhtikuuta2020 00:13:42.817] [Render thread/ERROR] [net.minecraft.client.MainWindow/]: @ Pre render
[27huhtikuuta2020 00:13:42.817] [Render thread/ERROR] [net.minecraft.client.MainWindow/]: 65539: Invalid key -1

I have zero knowledge what that means... Unsure if any of this is helpful information, but.. If i see anything else that might help i will make another issue, uh.. Feel free to close this if the information isn't providing any help.

**Comment by P3pp3rF1y** [comment] 2020-04-28 14:53
I don't immediately see anything in the list that should cause mod compatibility issues, but there are a few I haven't heard of / played with. However I don't have time to try figuring out which one may be causing issues for you. If you can narrow that down to what mod it is I can then take a look.

**Comment by BeyondElemental** [comment] 2020-05-19 02:13
I had the same problem and did some poking around. It looks like it might be The Midnight, but I didn't check to see if any other mods also caused the issue. This is reproducible with just the following:
```
forge-31.2.0
Reliquary-1.15.2-1.3.4.995.jar
themidnight-0.5.7-3.jar
```

From messing with the code, it looks like some events might not be firing in the expected order. In particular it looks like this check in `onItemRightClick` always fails on the client because `player.isSwingInProgress` is already true:
https://github.com/P3pp3rF1y/Reliquary/blob/138ed9fe470dfdca02a8fec0fa4044f1126f802b/src/main/java/xreliquary/items/EnderStaffItem.java#L210-L212
However, take that with a grain of salt; I just know enough to debug via logging.

**Comment by P3pp3rF1y** [comment] 2020-06-29 20:22
Well in that case this will need to be reported to midnight. I don't see a good reason why it should be swinging player's arm when another mod's item is right clicked and Ender staff needs to see if the player is swinging arm to not spawn multiple teleport projectiles. There would be a way to go around that on Reliquary side, but would require quite a few changes and I really don't like doing that because some other mod does weird things.

**Closed as completed by P3pp3rF1y** 2020-06-29 20:22 UTC
