### ISSUE TITLE
[1.10.2] Witherless Rose not granting wither immunity

### ISSUE THREAD

**Issue by SuddenlyARabbit** [P3pp3rF1y/Reliquary#227] opened 2017-04-01 22:37 UTC
Not sure exactly how witherless rose functions, but it seems to just remove wither every time it crops up?  Well, I'm running some Netherstar Generators from Extra Utilities 2, and with 3 speed upgrades they seem to apply Wither III too fast for the Witherless Rose to remove in time for me not to take damage.  I know this is a niche interaction with another mod, so if there's nothing you can/will do on your end that's fair.

**Comment by P3pp3rF1y** [comment] 2017-04-03 14:36
Looks like the generators must be doing more than just applying wither effect because when I try to splash myself with wither III it correctly cleans the wither effect without any damage dealt to player. Unfortunately I wasn't able to get extra utils to run in my dev environment so I can't debug what exactly it does, but I am certain it's a different type of damage and thus witherless rose wouldn't be able to protect you from it anyway.

**Comment by P3pp3rF1y** [comment] 2017-04-03 15:16
actually rereading your comment it looks like this has something to do with the speed of the generators or possibly when there's more generators or even just the fact that the effect gets applied by tileentities instead of potions. 
So I have just added a protection from wither damage when player has the rose on them. I will see in my SMP test environment if that helps, if it doesn't there isn't more that can be done as in that case the damage for sure isn't caused by wither effect.

**Comment by SuddenlyARabbit** [comment] 2017-04-03 23:58
Yeah, I think it's the speed of it being applied more than the quantity, based on how I've got things set up (a bunch of them in a row with 2 speed upgrades makes me not take any damage, the moment I stick a third speed upgrade in I start getting damaged).  And awesome!  Hopefully it works.

**Comment by P3pp3rF1y** [comment] 2017-04-05 21:48
So this is fixed in the latest version available on CF. I have tested generator with 20 upgrades in it and even though I occasionally see wither effect icon popup I don't get hurt at all.

**Closed as completed by P3pp3rF1y** 2017-04-05 21:48 UTC
