### ISSUE TITLE
Chalice OP?

### ISSUE THREAD

**Issue by Aceplante** [P3pp3rF1y/Reliquary#659] opened 2023-12-29 01:39 UTC
It giving raw hunger at the cost of health is okay I guess, but also giving enough saturation to immediately gain it back seems a bit much. Its basically an infinite food item

**Comment by P3pp3rF1y** [comment] 2024-03-27 19:50
Just tested this and yes you get healed by the saturation you just gained, but on normal it still doesn't heal you to the hearts you had before drinking so if you keep repeating that you will just kill yourself. Closing this as it works as intended in that case.

**Closed as completed by P3pp3rF1y** 2024-03-27 19:50 UTC
