### ISSUE TITLE
Reliquary incompatibility with Advent of Ascension mod.

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#625] opened 2023-04-30 01:17 UTC
Just like the title says, it's impossible to run Reliquary with Advent of Ascension. I will attach below the log file with what went wrong in hopes this will be fixed as I really do not want to give up on either, Reliquary is a mod I've been using for a lot of time and Advent of Ascension is a mod I recently stumbled upon and it's really grown on me. I will have to disable AoA for the time being and would love to know this has helped you in any way.

Have an amazing one!
[crash-2023-04-30_04.07.50-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/11360388/crash-2023-04-30_04.07.50-client.txt)

**Comment by P3pp3rF1y** [comment] 2023-04-30 22:19
What I can tell you is that some mod is causing an entity to have invalid data - brain field is set to null despite the fact it's non null and set by default to non null value by forge.
From you pointing out incompatibility it sounds like Advent of Ascension may be doing that so I recommend reporting to them to fix. I am going to leave this open for some time, but unless I hear about some good reason the data needs to be invalid like this I am going to just close.

**Comment by ghost** [comment] 2023-04-30 22:55
I understand, I will report it to them and be back when I have an answer.

**Comment by ghost** [comment] 2023-04-30 23:56
> What I can tell you is that some mod is causing an entity to have invalid data - brain field is set to null despite the fact it's non null and set by default to non null value by forge. From you pointing out incompatibility it sounds like Advent of Ascension may be doing that so I recommend reporting to them to fix. I am going to leave this open for some time, but unless I hear about some good reason the data needs to be invalid like this I am going to just close.

You can close this. The AoA dev said the mod won't ever be updated again for 1.19.2 version and he thinks the crash shouldn't affect the 1.19.4 version of the mod. I'll just play without one or the other on 1.19.2 until most mods get updated for 1.19.4 and beyond. Have a good one.

**Comment by Tslat** [comment] 2023-05-01 11:49
This is caused by improperly handling sided code

Why are you updating the brain's contents on the client side?

https://github.com/P3pp3rF1y/Reliquary/blob/8020e80f94e24a5afc5ae670c90ccd9d0c2b4615/src/main/java/xreliquary/items/MobCharmItem.java#L95

**Comment by ghost** [comment] 2023-05-01 18:15
I will be completely honest with you and tell you that I do not know what that means. I have not dibbled in anything related to that, I just installed both mods, I started the game, loaded the world, moved a few steps and got that error. If there's something I can do or not and you could tell me I'd greatly appreciate it, like can I stop updating the brain's contents? and what does that mean?

**Comment by P3pp3rF1y** [comment] 2023-05-01 20:27
> This is caused by improperly handling sided code
> 
> Why are you updating the brain's contents on the client side?
> 
> https://github.com/P3pp3rF1y/Reliquary/blob/8020e80f94e24a5afc5ae670c90ccd9d0c2b4615/src/main/java/xreliquary/items/MobCharmItem.java#L95

That code definitely doesn't need to run on client, but as far as I can see the related event is only ever fired as a result of ai running which as far as I have experience only runs server side. Why do you believe this is being run client side?

And at the same time `getBrain` isn't marked as nullable so it should always return instance of brain.

**Comment by P3pp3rF1y** [comment] 2023-05-01 20:30
actually I missed the other place where this code is called from which is actually called on tick even that definitely runs client side and that's something I can improve in terms of performance there, but the thing with brain being returned as null still shouldn't happen even on client side.

**Comment by Tslat** [comment] 2023-05-01 21:20
It happens because SBL doesn't instantiate the brain on the client side because at no point should it be used, and it performs a lot of work for no reason

I'll look into dummy-instantiating something to reduce this kind of issue in the future, but you still shouldn't be doing server-side work on the client. This isn't about performance, this is about code-safety

**Comment by ghost** [comment] 2023-05-01 22:28
But is there something I can do? I didn't do server-side work on the client, I just installed the mods directly from the curse forge app and that was it, I didn't meddle in any code client-side or server-side, didn't change anything.

**Comment by P3pp3rF1y** [comment] 2023-05-02 06:16
@AlexanderI32 there's nothing you can do with the two mods in their current state in 1.19.2. to work together. One will have to change to fix this for you.

**Comment by ghost** [comment] 2023-05-02 13:27
I understand, i'll play without one or the other since neither will fix for 1.19.2 and play with them both in future versions of Mc. Thanks a lot, have an amazing one!

**Closed as not planned** 2023-12-06 12:47 UTC
Labels: need info
