### ISSUE TITLE
Lilypad of Fertility Dupe Bug 2.0 [SpongeForge]

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#266] opened 2017-11-19 01:29 UTC
It's about this topic: https://github.com/P3pp3rF1y/Reliquary/issues/265

Im sry but the problem is still here
MC-Version: 1.12.2
Reliquary-Version: Reliquary-1.12.2-1.3.4.719

n singleplayer everything works wonderfully. only on our server it seems to be that the lilypad doubles.

our servers are running on spongeforge ...

**Comment by P3pp3rF1y** [comment] 2017-11-19 07:42
And I have just retested with sponge server and can't see the issue either. 
Are you sure that you are able to recreate this with just reliquary so that you're sure that no other mod affects it?

**Comment by P3pp3rF1y** [comment] 2017-11-30 19:19
Any update you have on this? I will close the issue soon if I don't have any additional info on how I could reproduce.

**Comment by ghost** [comment] 2017-12-11 15:55
so it is still. why I do not know. in the single player it does not work but on the spongeforge server. that's the only thing I know. Inventory has been completely emptied and there are no effects.

try downloading the modpack and try to test it. Maybe you will find a note.

**Comment by ghost** [comment] 2017-12-11 15:57
other users on our server reported this to me and after I tested it I wrote you the issue

**Comment by ghost** [comment] 2017-12-11 16:17
One Update
Reliquary-Version: Reliquary-1.12.2-1.3.4.724

**Comment by P3pp3rF1y** [comment] 2017-12-11 16:26
I trust that you can recreate that with modpack, but I honestly don't have time to go through mods there and figure out which mod is causing this interaction issue.
Can you actually recreate that with just sponge and reliquary?
And if not can you limit it down to what mod is causing the issue? I can then take a look at what's happening there.

**Comment by P3pp3rF1y** [comment] 2018-02-16 15:43
Closing due to non responsiveness

**Closed as completed by P3pp3rF1y** 2018-02-16 15:43 UTC
