### ISSUE TITLE
Crash when wear charm

### ISSUE THREAD

**Issue by dagantang** [P3pp3rF1y/Reliquary#371] opened 2019-03-03 15:49 UTC
https://pastebin.com/XDzuS90b

**Comment by Inurosen** [comment] 2019-04-21 12:50
To make this more clear the game crashes when you hit a mob you are wearing charm for.

**Comment by Inurosen** [comment] 2019-04-25 06:29
Duplicate of #355

**Comment by P3pp3rF1y** [comment] 2020-06-29 20:25
#355 was fixed a long time ago, closing...

**Closed as completed by P3pp3rF1y** 2020-06-29 20:25 UTC
