### ISSUE TITLE
There is still a crash on initialization [1.16.5]

### ISSUE THREAD

**Issue by McSquizzleswag** [P3pp3rF1y/Reliquary#544] opened 2022-01-23 14:31 UTC
I brought up this problem with an astral sorcery dev and they had this to say

> AS isnt even in that trace until entirely too many other mods touch it. Looks like reliquary is the issue, not SSN or AS.
> Issue lies here:
java.lang.NullPointerException: Initializing game
at xreliquary.items.VoidTearItem$1.getCapability(VoidTearItem.java:90) ~[?:1.16.5-1.3.5.1100] {re:classloading}
at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:102) ~[?:?] {re:classloading}
at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:174) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM}

**Comment by P3pp3rF1y** [comment] 2022-01-24 07:50
This issue was caused by Electrodynamics before not astral sorcery as far as I know (or it's a different one and in that case I will need a full crash log but this part of crash is the exact same as the one you have reported last month). Have electrodynamics fixed this?

This one of the crashes it causes https://github.com/refinedmods/refinedstorage/issues/3129 but as said before it causes crashes with simple storage networks as well as other mods. The issue is they call tooltip code of items way too early before a lot of other stuff has a chance to initialize.

**Comment by McSquizzleswag** [comment] 2022-01-24 12:48
The dev of Electrodynamics did release a new version for 1.16.5 but the crash still persists. In fact it's still crashing the same way with reliquary and astral sorcery appearing in the crash log and removing those two just shifts it over to simple storage network appearing in the log

**Comment by McSquizzleswag** [comment] 2022-01-24 12:58
Really nothing has changed and the logs wouldn't show any different

**Comment by McSquizzleswag** [comment] 2022-01-24 13:11
[crash-2022-01-22_13.24.21-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/7925751/crash-2022-01-22_13.24.21-client.txt)
[latest.log](https://github.com/P3pp3rF1y/Reliquary/files/7925754/latest.log)

**Comment by P3pp3rF1y** [comment] 2022-01-24 21:00
alright and does downgrading Electrodynamics to 1.16.5-0.4.0-1 fix the crash for you?

**Comment by P3pp3rF1y** [comment] 2022-01-24 21:01
taken that information from here https://github.com/aurilisdev/Electrodynamics/issues/97

**Comment by McSquizzleswag** [comment] 2022-01-24 21:11
Downgrading used to fix it, but this is a public modpack, I can't update the pack and leave electrodynamics and it's other mods on an older version

**Comment by McSquizzleswag** [comment] 2022-01-24 21:13
I'm gonna try updating the pack to 1.18.1, as the server it's used for is able to be updated, maybe it'll be different maybe it won't. Aurilisdev even said they aren't supporting 1.16.5 anymore

**Comment by P3pp3rF1y** [comment] 2022-01-24 21:24
I mean unless I see that something I am doing is really wrong and needs fixing I am not going to fix this. Reliquary works well with so many other mods in so many modpacks and it's just the newer versions of Electrodynamics that cause issues so I don't see how Reliquary would be at fault here especially that other big mods are having same issue with Electrodynamics.

**Comment by P3pp3rF1y** [comment] 2022-01-25 19:35
I have tried looking more into this and do some debugging and what is happening is that once Electrodynamics is added it causes forge to not load capabilities early enough before tooltips of items are queried which in turn causes this crash. There is a massive amount of changes that were made to that mod and I don't have time figuring out what they are doing so I am going to close as not to be fixed on my side as those capabilities should really be loaded before tooltip is triggered.

**Closed as completed by P3pp3rF1y** 2022-01-25 19:35 UTC
Labels: wontfix
