### ISSUE TITLE
[1.15.2] Some mob drops not dropping

### ISSUE THREAD

**Issue by phlane** [P3pp3rF1y/Reliquary#409] opened 2020-04-14 21:42 UTC
Mob drops from zombies and skeletons drop, but so far I have not been able to get any other drops. Are they incredibly rare for other mobs? I have killed quite a few.

**Comment by P3pp3rF1y** [comment] 2020-04-15 17:55
They are set at about 10%, if you have  20 - 30  or so of a mob you should get at least one, but of course it's randomized so luck may be against you even then. If you actually have an issue with some mob just add that info here, but please make sure you have killed enough of those mobs.

**Comment by P3pp3rF1y** [comment] 2020-04-15 17:58
btw, just tried with blaze and spider and definitely getting drops there.

**Comment by phlane** [comment] 2020-04-15 22:59
What kinds of other mods would conflict with mod drops? I have quite a few other mods and I've been trying to determine if its one of them or not.

**Comment by P3pp3rF1y** [comment] 2020-04-16 08:50
I don't know of any from the top of my mind especially not in 1.15 so you will need to experiment with that. but let me know if you find one that causes this for you.

**Comment by gfreitash** [comment] 2020-04-27 03:36
Slimes are not dropping slime pearl, and yeah, i've killed quite a few

**Comment by P3pp3rF1y** [comment] 2020-04-27 07:47
@Riosodu Again this is working correctly with just Reliquary in the pack so it's something in your mod pack that's causing this.
@Effectstudios Sorry, but I am not aware of any mods that would be causing something like this, but I haven't played 1.15 packs yet. I would look for anything that does something with loot, changes player attack in any way or something like that, but ultimately you may need to try removing mods and see if the issue is still there.

**Comment by CmdrFluffy** [comment] 2020-08-15 11:34
I am having the same issue on my server
we added the reliquary mod after the initial world was created, it was chosen as a replacement for some corails stuff that we were getting rid of, and in a new world I get the drops, but not in the existing world/server, I copied the server files over to a single player world and optimized thinking that would get the drops to start, but they do not and this effects both single player and server, but again on a new world I get the drops with no issue

**Comment by CmdrFluffy** [comment] 2020-08-15 11:34
if there is any information I can provide further please let me know

**Comment by CmdrFluffy** [comment] 2020-08-15 11:36
1.15.2 server
31.2.31 forge

**Comment by P3pp3rF1y** [comment] 2020-08-26 20:46
This is really odd, reliquary uses standard loot tables like vanilla does so there must be something that potentially caches the loot tables that can drop and when other mods are added to the pack that add loot tables they don't get a chance to spawn their stuff. but really hard for me to tell without anything to go on. Reliquary alone isn't an issue as far as I can see unless you're saying that you tried running the server with just vanilla + reliquary and no other mod and still had the issue. So there's some other mod that causes this.

**Comment by P3pp3rF1y** [comment] 2020-10-31 09:50
Drops are working and this really looks like a modpack issue, so closing if you figure out how to recreate with just reliquary or that reliquary is at fault for some reason feel free to reopen.

**Closed as completed by P3pp3rF1y** 2020-10-31 09:50 UTC
Labels: unable to recreate, need info
