### ISSUE TITLE
Tool Tip on Void Tear

### ISSUE THREAD

**Issue by Watchful1** [P3pp3rF1y/Reliquary#178] opened 2016-10-17 21:59 UTC
Currently there is no way to differentiate void tears unless they are actually in your hand. It makes it fairly hard to keep track of a bunch of them in a chest.

Or just render the item they are storing when you hold shift, regardless of where they are.

**Comment by P3pp3rF1y** [comment] 2016-10-18 00:32
Which version are you referring to? I am pretty sure latest one has both tooltip and display of contents when shift is pressed. 
You mean 1.7.10 one?

**Comment by Watchful1** [comment] 2016-10-18 00:37
1.10.2-1.3.3.571

When the item is in a chest. Here's a screenshot.

![Void Tear](http://i.imgur.com/cLUotTe.png)

Holding shift doesn't do anything.

**Comment by P3pp3rF1y** [comment] 2016-10-18 01:21
So that looks like some mod interaction going on that blocks the functionality. I can definitely see void tear contents on shift whatever inventory they are in. And you see to be missing tooltip there as well. This is what I see by default when looking at the void tear and that's the way it has been since 1.7. 
![image](https://cloud.githubusercontent.com/assets/2079526/19461066/8d53f318-94e1-11e6-99f6-31269f88591b.png)

I am guessing you have some mod there that gets rid of tooltips and perhaps turns off shift as well?

**Comment by Watchful1** [comment] 2016-10-20 00:11
I'll try to narrow this down and figure out what mod's causing it. I'll reopen the task it I do.

**Comment by MrNinja93** [comment] 2016-10-22 04:40
@Watchful1  If it helps track the cause down my modlist without that problem, somewhat out of date mods but may help you narrow the field. 

[Modlist.txt](https://github.com/P3pp3rF1y/Reliquary/files/545596/Modlist.txt)

**Comment by P3pp3rF1y** [comment] 2016-10-22 10:05
Do you perhaps have IKWILA installed? That could definitely explain missing tooltip. Not sure if it would cause the shift to break though.

**Comment by Watchful1** [comment] 2016-10-22 19:37
I was able to reproduce this with just Reliquary, but only on a server. It didn't happen on ssp.

**Comment by P3pp3rF1y** [comment] 2016-10-22 19:48
I was just able to recreate that as part of testing of the new release. will take a look at what is causing this. Very odd one.

**Comment by MrNinja93** [comment] 2016-10-22 19:50
Checked on my server running version 568 and it works as intended so anything changed since that build

**Comment by P3pp3rF1y** [comment] 2016-10-22 20:01
Are you checking that when in your inventory or when it's in chest/dispenser or some other inventory?

The only difference between 568 and 571 which is last public build is a fix to void tear where it wasn't placing blocks server side and that shouldn't affect how tooltips are displayed, btw.

**Comment by MrNinja93** [comment] 2016-10-22 20:06
Derp... Yeah in inventories its broken

**Comment by P3pp3rF1y** [comment] 2016-10-22 20:09
I am pretty sure that this is related to item handler capability (that it uses behind the scenes) not being synced to client when in inventories. I will see what I can do about that. I am pretty sure there should be a way to sync that on server as well.

**Comment by P3pp3rF1y** [comment] 2016-10-22 21:13
btw, I didn't mention this previously, but thanks a lot for testing this stuff out and reporting it here. 
This helps a lot :)

**Comment by P3pp3rF1y** [comment] 2016-10-31 13:12
This is now fixed in the latest release on CF https://minecraft.curseforge.com/projects/reliquary-v1-3

**Closed as completed** 2016-10-31 13:13 UTC
