### ISSUE TITLE
Reliquary Ticking Entity Due to Charm

### ISSUE THREAD

**Issue by ChosenArchitect** [P3pp3rF1y/Reliquary#682] opened 2024-04-12 14:04 UTC
Issue thread:
https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/123

**Comment by P3pp3rF1y** [comment] 2024-04-12 14:38
This one as well as CME that also happened is fixed in the latest release available on CF https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations/files/5253707

**Closed as completed by P3pp3rF1y** 2024-04-12 14:38 UTC

**Comment by ChosenArchitect** [comment] 2024-04-14 02:27
Thanks bud will update!

**Comment by Maxi90909** [comment] 2024-06-09 16:42
The issue is still present with horror mods like the knocker by M_Productions or mods from CEOofAutism.
