### ISSUE TITLE
Incompatible with latest Astral Sorcery 1.14.0 (1.16.5)

### ISSUE THREAD

**Issue by Diversion98** [P3pp3rF1y/Reliquary#574] opened 2022-06-01 07:13 UTC
Hi,

Yesterday there was a new update for Astral Sorcery.
After this update the game crashes on startup back to desktop.
This issue is allready reported here: https://github.com/HellFirePvP/AstralSorcery/issues/1952

Now when I disabled Reliquary in my modpack, the modpack launches just fine.
I also made a new test pack that just have the mods that are required and still crashes so I know its one of the following mods:

Forge 36.2.35
Astral Sorcery 1.14.0
Curios API (Forge) 4.0.5.3
ObserverLib 1.5.3
Reliquary Reincarnations 1.3.5.1124

Crash log: https://paste.gg/p/anonymous/47bfff2dc37540cead27e79891163c41
Latest.log: https://paste.gg/p/anonymous/7494f334f1f34c6298f6d2c33b62b60d

Cheers

**Comment by FoxMcloud5655** [comment] 2022-06-01 10:28
Can confirm that this issue occurs on the following versions:
* Astral Sorcery  - 1.14.0
* Reliquary - 1.3.5.1124

The following relevant entry in the crash report:
```
java.lang.NullPointerException: Initializing game
	at xreliquary.items.VoidTearItem$1.getCapability(VoidTearItem.java:90) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:88) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:160) ~[?:?] {re:computing_frames,re:mixin,re:classloading,re:ChickenASM}
	at xreliquary.util.InventoryHelper.getItemHandler(InventoryHelper.java:370) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at xreliquary.util.InventoryHelper.getFromHandler(InventoryHelper.java:374) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at xreliquary.items.VoidTearItem.getFromHandler(VoidTearItem.java:435) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at xreliquary.items.VoidTearItem.isEmpty(VoidTearItem.java:563) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at xreliquary.items.VoidTearItem.isEmpty(VoidTearItem.java:555) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at xreliquary.items.VoidTearItem.getItemStackLimit(VoidTearItem.java:70) ~[?:1.16.5-1.3.5.1124] {re:classloading}
	at net.minecraft.item.Item.func_77616_k(Item.java:252) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:forge:crossbows.8,re:mixin,pl:accesstransformer:B,xf:fml:forge:crossbows.8,re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:APP:pehkui.mixins.json:reach.compat116plus.ItemMixin,pl:mixin:APP:ftblibrary-common.mixins.json:ItemMixin,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:APP:charm.mixins.json:accessor.ItemAccessor,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemMixin,pl:mixin:A}
	at hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper.lambda$canHaveDynamicEnchantment$0(DynamicEnchantmentHelper.java:180) ~[?:task ':jar' property 'archiveVersion'] {re:mixin,re:classloading}
	at hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper$$Lambda$31905/1455383227.run(Unknown Source) ~[?:?] {}
	at hellfirepvp.astralsorcery.common.event.EventFlags$BooleanFlag.executeWithFlag(EventFlags.java:57) ~[?:task ':jar' property 'archiveVersion'] {re:classloading}
	at hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper.canHaveDynamicEnchantment(DynamicEnchantmentHelper.java:172) ~[?:task ':jar' property 'archiveVersion'] {re:mixin,re:classloading}
	at hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper.addNewLevels(DynamicEnchantmentHelper.java:140) ~[?:task ':jar' property 'archiveVersion'] {re:mixin,re:classloading}
```

**Comment by P3pp3rF1y** [comment] 2022-06-04 07:35
Have you actually tried with just those two mods? this very much reminds me of multiple issues reported here which were caused by ElectroDynamics by any chance have you got it in the pack?

**Comment by FoxMcloud5655** [comment] 2022-06-04 08:23
No, I can promise you I do not have that mod in my modpack, Duality, where I have this same crash.

**Comment by FoxMcloud5655** [comment] 2022-06-04 08:44
I also can confirm that it IS these exact mods and versions that cause this issue:
```
Mod List: 
	forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
	astralsorcery-1.16.5-1.14.0.jar                   |Astral Sorcery                |astralsorcery                 |task ':jar' property|COMMON_SET|Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
	forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	reliquary-1.16.5-1.3.5.1124.jar                   |Reliquary                     |xreliquary                    |1.16.5-1.3.5.1124   |COMMON_SET|Manifest: NOSIGNATURE
	curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |COMMON_SET|Manifest: NOSIGNATURE
	observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib    
```
Astral Sorcery switched to using mixins instead of using JS ASM, likely causing this specific crash to occur.  It has sense been reverted in version 1.14.1 to temporarily fix this issue until the root problem can be resolved.

**Comment by P3pp3rF1y** [comment] 2022-09-23 07:26
this issue is fixed in 1.18+ now. I don't really intend to fix this in 1.16 as this is probably the only report and I want to focus on other mods instead

**Comment by FoxMcloud5655** [comment] 2022-09-23 07:47
That's fair; a good bit of modpacks have moved on to 1.18.2, including my own.

**Comment by P3pp3rF1y** [comment] 2022-09-23 08:37
this is now released

**Closed as completed by P3pp3rF1y** 2022-09-23 08:37 UTC
Labels: fixed in development
