### ISSUE TITLE
tome of alkahestry charging dupe

### ISSUE THREAD

**Issue by Aaal-E** [P3pp3rF1y/Reliquary#497] opened 2021-01-27 13:24 UTC
When there is an active tome of alkahestry in the inventory, full stacks of redstone or redstone blocks in the inventory, and the same item in an itemstack on the ground in reach of the player, the alkahestry tome charges without consuming redstone.

using reliquary 1.16.3 - 1.3.4.1061, direwolf20 1.16 pack in the ftbapp.

**Comment by P3pp3rF1y** [comment] 2021-01-27 13:53
Tried to recreate this, but I am unable to with Reliquary. I am not 100% clear of stack within a reach (how many blocks away / is player picking the stack up, ...), but this sounds like some other mod is causing the issue. If you can figure out which one it is let me know and I will take a look if there's anything wrong on Reliquary side.

**Comment by NekoChanPvP** [comment] 2021-02-16 19:04
o/ I got more info on the crash. I have the same issue while playing all the mods 6. basically, when you toggle auto consume and open your inventory, your game will crash. I did this many times and im not sure if its caused by this, but after a few tries it corrupted config files to the point of the game not launching, if you need more details i can easily provide them, dm me on Nqkia#3310 and i can send you my logs

**Comment by P3pp3rF1y** [comment] 2021-04-04 13:52
no additional info provided for a long time so closing this

**Closed as completed by P3pp3rF1y** 2021-04-04 13:52 UTC
Labels: need info
