### ISSUE TITLE
crash on server startup

### ISSUE THREAD

**Issue by BugmanBugman** [P3pp3rF1y/Reliquary#556] opened 2022-03-19 18:58 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/19/22, 1:49 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.0.19-universal.jar%23143!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.0.19-universal.jar%23143!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220228.144236-srg.jar%23139!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.2-40.0.19.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
-- MOD reliquary --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.19.jar%23141!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.19.jar%23140!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraft/client/model/Model
		at reliquary.init.ModItems.<clinit>(ModItems.java:153) ~[reliquary-1.18.2-2.0.1.1129.jar%23117!/:1.18.2-2.0.1.1129] {re:classloading}
		at reliquary.Reliquary.<init>(Reliquary.java:57) ~[reliquary-1.18.2-2.0.1.1129.jar%23117!/:1.18.2-2.0.1.1129] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.19.jar%23141!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.19.jar%23140!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: reliquary-1.18.2-2.0.1.1129.jar
	Failure message: Reliquary (reliquary) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.18.2-2.0.1.1129
	Mod Issue URL: https://github.com/p3pp3rF1y/reliquary/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.model.Model
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at reliquary.init.ModItems.<clinit>(ModItems.java:153) ~[reliquary-1.18.2-2.0.1.1129.jar%23117!/:1.18.2-2.0.1.1129] {re:classloading}
	at reliquary.Reliquary.<init>(Reliquary.java:57) ~[reliquary-1.18.2-2.0.1.1129.jar%23117!/:1.18.2-2.0.1.1129] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.19.jar%23141!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.19.jar%23140!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 7664180320 bytes (7309 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 520
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: DriverVersion=24.20.100.6286
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 15227.52
	Virtual memory used (MB): 12875.78
	Swap memory total (MB): 7166.37
	Swap memory used (MB): 280.75
	JVM Flags: 20 total; -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		adaptive_performance_tweaks_core_1.18.2-3.0.0.jar |APTweaks: Core                |adaptive_performance_tweaks_co|3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		netherportalfix-forge-1.18-9.0.0.jar              |NetherPortalFix               |netherportalfix               |9.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		curiousshulkerboxes-forge-1.18.1-4.2.0.0.jar      |Curious Shulker Boxes         |curiousshulkerboxes           |1.18.1-4.2.0.0      |COMMON_SET|Manifest: NOSIGNATURE
		connectivity-1.18.2-2.7.jar                       |Connectivity Mod              |connectivity                  |1.18.2-2.7          |COMMON_SET|Manifest: NOSIGNATURE
		Incendium_v5.0.3.jar                              |Incendium                     |incendium                     |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		InsaneLib-1.4.5-mc1.18.2.jar                      |InsaneLib                     |insanelib                     |1.4.5               |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.5.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.5        |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.11.1-1.18.2.jar                         |Citadel                       |citadel                       |1.11.1              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.17.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.3              |COMMON_SET|Manifest: NOSIGNATURE
		beaconsforall-forge-1.18.1-5.2.0.0.jar            |Beacons For All               |beaconsforall                 |1.18.1-5.2.0.0      |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-28.jar                      |YUNG's API                    |yungsapi                      |1.18.2-Forge-28     |COMMON_SET|Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.0.7.jar                 |Bookshelf                     |bookshelf                     |13.0.7              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.18.2.1.4.1.jar                   |Guard Villagers               |guardvillagers                |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		adaptive_performance_tweaks_gamerules_1.18.2-3.0.0|APTweaks: Gamerules           |adaptive_performance_tweaks_ga|3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		ProgressiveBosses-3.5.5-mc1.18.2.jar              |Progressive Bosses            |progressivebosses             |3.5.5               |COMMON_SET|Manifest: NOSIGNATURE
		jeed-1.18.2-1.9.jar                               |Just Enough Effect Description|jeed                          |1.18.2-1.9          |COMMON_SET|Manifest: NOSIGNATURE
		balm-3.0.1+0.jar                                  |Balm                          |balm                          |3.0.1+0             |COMMON_SET|Manifest: NOSIGNATURE
		SnowRealMagic-1.18.2-forge-4.0.0.jar              |Snow! Real Magic!             |snowrealmagic                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		revampedwolf-1.18.2-1.2.0.jar                     |RevampedWolf                  |revampedwolf                  |1.18.2-1.2.0        |COMMON_SET|Manifest: NOSIGNATURE
		ExperienceBugFix-1.18-1.38.0.2.jar                |Experience Bug Fix            |experiencebugfix              |1.38.0.2            |COMMON_SET|Manifest: NOSIGNATURE
		AirHop-v3.2.0-1.18.2-Forge.jar                    |Air Hop                       |airhop                        |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		TinySkeletons-v3.2.0-1.18.2-Forge.jar             |Tiny Skeletons                |tinyskeletons                 |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		repurposed_structures_forge-5.0.4+1.18.2.jar      |Repurposed Structures         |repurposed_structures         |5.0.4+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		morevillagers-FORGE-1.18.2-3.2.0.jar              |More Villagers                |morevillagers                 |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		GoldenAgeCombat-v3.3.0-1.18.2-Forge.jar           |Golden Age Combat             |goldenagecombat               |3.3.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BiomesOPlenty-1.18.2-16.0.0.107-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.107   |COMMON_SET|Manifest: NOSIGNATURE
		moyai-1.18.2-1.1.3.jar                            |Moyai                         |moyai                         |1.18.2-1.1.3        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.6.3.jar                   |Curios API                    |curios                        |1.18.2-5.0.6.3      |COMMON_SET|Manifest: NOSIGNATURE
		randomite-1.18.2-1.1.2.jar                        |Randomite Classic             |randomite                     |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		spyglass_improvements-1.1.1+mc1.18.1+forge.jar    |Spyglass Improvements         |spyglass_improvements         |1.1.1+mc1.18.1      |COMMON_SET|Manifest: NOSIGNATURE
		villagertools-1.18-1.0.2.jar                      |villagertools                 |villagertools                 |1.18-1.0.2          |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		architectury-4.1.32.jar                           |Architectury                  |architectury                  |4.1.32              |COMMON_SET|Manifest: NOSIGNATURE
		mountedpearl-1.18-1.0.0.jar                       |Mounted Pearl                 |mountedpearl                  |1.18-1.0.0          |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		adaptive_performance_tweaks_items_1.18.2-3.0.0.jar|APTweaks: Items               |adaptive_performance_tweaks_it|3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.12.jar                    |GeckoLib                      |geckolib3                     |3.0.12              |COMMON_SET|Manifest: NOSIGNATURE
		EnchantingInfuser-v3.2.0-1.18.2-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		TradingPost-v3.2.0-1.18.2-Forge.jar               |Trading Post                  |tradingpost                   |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		radium-0.7.9.jar                                  |Radium                        |radium                        |0.7.9               |COMMON_SET|Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |COMMON_SET|Manifest: NOSIGNATURE
		Kiwi-1.18.2-forge-6.0.1.jar                       |Kiwi                          |kiwi                          |6.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		adaptive_performance_tweaks_spawn_1.18.2-3.0.0.jar|APTweaks: Spawn               |adaptive_performance_tweaks_sp|3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		dusk-1.18.1-1.8.jar                               |Dusk Mod                      |dusk                          |1.18.1-1.8          |COMMON_SET|Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.18.2-1.4.12.jar             |Biome Makeover                |biomemakeover                 |1.18.2-1.4.12       |COMMON_SET|Manifest: NOSIGNATURE
		flatbedrock-1.4.2-build.9+mc1.18.2.jar            |Flat Bedrock                  |flatbedrock                   |1.4.2-build.9+mc1.18|COMMON_SET|Manifest: NOSIGNATURE
		ConfigMenusForge-v3.2.0-1.18.2-Forge.jar          |Config Menus for Forge        |configmenusforge              |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		EasyMagic-v3.3.0-1.18.2-Forge.jar                 |Easy Magic                    |easymagic                     |3.3.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.2-9.5.3.143.jar                          |Just Enough Items             |jei                           |9.5.2.136           |COMMON_SET|Manifest: NOSIGNATURE
		VisualWorkbench-v3.2.0-1.18.2-Forge.jar           |Visual Workbench              |visualworkbench               |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		UniversalBoneMeal-v3.0.2-1.18.2-Forge.jar         |Universal Bone Meal           |universalbonemeal             |3.0.2               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		AttributeFix-Forge-1.18.2-14.0.1.jar              |AttributeFix                  |attributefix                  |14.0.1              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		differentiate-1.18.2-1.0.3.jar                    |Differentiate                 |differentiate                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |COMMON_SET|Manifest: NOSIGNATURE
		Paxi-Forge-1.18.1-1.0.jar                         |Paxi                          |paxi                          |1.18.1-1.0          |COMMON_SET|Manifest: NOSIGNATURE
		colytra-forge-1.18.1-5.2.0.1.jar                  |Colytra                       |colytra                       |1.18.1-5.2.0.1      |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-1.18.2-4.0.6.jar                        |Artifacts                     |artifacts                     |1.18.2-4.0.6        |COMMON_SET|Manifest: NOSIGNATURE
		champions-forge-1.18.2-2.1.2.0.jar                |Champions                     |champions                     |1.18.2-2.1.2.0      |COMMON_SET|Manifest: NOSIGNATURE
		curioofundying-forge-1.18-5.3.0.0.jar             |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		farsightedmobs-forge-1.1-1.18.jar                 |Farsighted Mobs               |farsightedmobs                |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		lock_and_key-1.18.2-1.1.0.jar                     |Lock & Key                    |lock_and_key                  |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		lazydfu-1.0-1.18+.jar                             |LazyDFU                       |lazydfu                       |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		BeeFix-1.18-1.0.0.5.jar                           |Bee Fix                       |beefix                        |1.0.0.5             |COMMON_SET|Manifest: NOSIGNATURE
		Terralith_v2.2.1a.jar                             |Terralith                     |terralith                     |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		adaptive_performance_tweaks_player_1.18.2-3.0.0.ja|APTweaks: Player              |adaptive_performance_tweaks_pl|3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		scuba_gear-1.18.2-1.0.4.jar                       |Scuba Gear                    |scuba_gear                    |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		dash-1.18-1.0.1.jar                               |Dash                          |dash                          |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		selene-1.18.2-1.14.1.jar                          |Selene                        |selene                        |1.18.2-1.14.1       |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.3.0.jar                  |Supplementaries               |supplementaries               |1.18.2-1.3.0        |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.18.2-2.1.50a-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.50-1.18.2       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.93.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.93     |COMMON_SET|Manifest: NOSIGNATURE
		CooperativeAdvancements-1.18.1-1.2.2.jar          |Cooperative Advancements      |cooperativeadvancements       |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		Companion-1.18.2-forge-2.0.0.jar                  |Companion                     |companion                     |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.18.2-5.0.1.jar                             |Jade                          |jade                          |5.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.0.19-universal.jar                |Forge                         |forge                         |40.0.19             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		snowyspirit-1.18.2-1.2.1.jar                      |Snowy Spirit                  |snowyspirit                   |1.18.2-1.2.1        |COMMON_SET|Manifest: NOSIGNATURE
		Ksyxis-Forge1.17-1.1.jar                          |Ksyxis                        |ksyxis                        |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		lepton-1.18.2-2.0.0.jar                           |Lepton                        |lepton                        |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		actuallycompatible-0.1.2.jar                      |Actually Compatible           |actuallycompatible            |0.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.18.2-1.0.40.jar                         |Iceberg                       |iceberg                       |1.0.40              |COMMON_SET|Manifest: NOSIGNATURE
		reliquary-1.18.2-2.0.1.1129.jar                   |Reliquary                     |reliquary                     |1.18.2-2.0.1.1129   |ERROR     |Manifest: NOSIGNATURE
		ecologics-FORGE-1.18.1-1.3.1.jar                  |Ecologics                     |ecologics                     |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		brutalbosses-1.18.1-4.0.jar                       |brutalbosses mod              |brutalbosses                  |1.18.1-4.0          |COMMON_SET|Manifest: NOSIGNATURE
		ngv-1.2.0.jar                                     |Nether Gold Veins             |ngv                           |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		lava_monster-1.18.2-1.0.11.jar                    |Lava Monster                  |lava_monster                  |1.0.11              |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.40.jar                   |Polymorph                     |polymorph                     |1.18.1-0.40         |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.2-344.jar                                 |Quark                         |quark                         |3.2-344             |COMMON_SET|Manifest: NOSIGNATURE
		adaptive_performance_tweaks_1.18.2-3.0.0.jar      |APTweaks (Bundle)             |adaptive_performance_tweaks   |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		hardcorerevival-forge-1.18-8.0.0.jar              |Hardcore Revival              |hardcorerevival               |8.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Regrowth-1.18.2-1.40.0.27.jar                     |Regrowth                      |regrowth                      |1.18.2-1.40.0.27    |COMMON_SET|Manifest: NOSIGNATURE
		UniversalEnchants-v3.0.3-1.18.2-Forge.jar         |Universal Enchants            |universalenchants             |3.0.3               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		HunterIllager-1.18.2-4.0.0.jar                    |Hunter Illager                |hunterillager                 |1.18.2-4.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		creeperoverhaul-1.18.2-1.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-4.2.0-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		DamageTilt-1.18-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v3.3.2-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.2               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		bettergolem-1.18.2-1.1.0.jar                      |Better Golem                  |bettergolem                   |1.18.2-1.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		step-1.18-1.1.0.jar                               |Step                          |step                          |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		domesticationinnovation-1.1.0-1.18.2.jar          |Domestication Innovation      |domesticationinnovation       |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 3b83c7c7-fa08-400b-b79b-84af5af09a19
	FML: 40.0
	Forge: net.minecraftforge:40.0.19

**Comment by P3pp3rF1y** [comment] 2022-03-19 21:20
Duplicate of #555

**Closed as completed by P3pp3rF1y** 2022-03-19 21:20 UTC
