### ISSUE TITLE
[1.10.2-1.3.3.585] java.lang.ClassCastException: xreliquary.items.ItemVoidTear$VoidTearListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP

### ISSUE THREAD

**Issue by RealGrep** [P3pp3rF1y/Reliquary#186] opened 2016-11-01 06:45 UTC
Every pattern I create in the AE2 pattern grid suddenly started being "Invalid pattern". So I looked into the logs, and found this on the server side:

http://hastebin.com/uratutupot.sql

Basically:
java.util.concurrent.ExecutionException: java.lang.ClassCastException: xreliquary.items.ItemVoidTear$VoidTearListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP

Not entirely sure the issue is on your end, but it only appeared with the latest version you just released, and that did try to fix something to do with Void Tears.

EDIT: Indeed, backing off to the previous version of Reliquary allows me to make AE2 patterns, once again.

**Comment by BrokenHearted2** [comment] 2016-11-01 10:05
Same problem here.

**Comment by P3pp3rF1y** [comment] 2016-11-01 16:48
So I have included new logic for void tear and that's what is breaking AE now. 

But the cause is really that AE expects crafting listeners to be just players when they can be anything so a check will need to be added on AE side to make sure that it's handling only players in this part of the code https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/container/implementations/ContainerPatternTerm.java#L498

**Comment by ozhound** [comment] 2016-11-03 08:24
This isnt only related to AE, we get a server crash when someone tries to use Chisel and Bits.
https://paste.ubuntu.com/23419764/

**Comment by RealGrep** [comment] 2016-11-03 08:31
@ozhound , update your C&B. It's already fixed there: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/159

**Comment by b0bst3r** [comment] 2016-11-10 17:37
Not only the mods above but I get the same when accessing Inductive Automation machines http://pastebin.ubuntu.com/23457117/ we've had similar crashed with other mods too.

**Comment by P3pp3rF1y** [comment] 2016-11-10 22:18
Sure, but did you report this to the mod authors? Because the issue here is really that they just assume they will only ever get player from a collection that can have pretty much anything in it.

**Comment by P3pp3rF1y** [comment] 2016-12-22 00:42
Closing as the other mods have closed the interaction issues here.

**Closed as completed by P3pp3rF1y** 2016-12-22 00:42 UTC
