### ISSUE TITLE
mod compatibility issues between rarmor and reliquary void tear crashing client(Reliquary-1.11.2-1.3.3.635)

### ISSUE THREAD

**Issue by SDUBZ** [P3pp3rF1y/Reliquary#219] opened 2017-02-08 12:58 UTC
i was trying to apply a solar upgrade when i got this crash mention both mods causing a crash, gets affected after sometime in the players inventory gui and switched to rarmor gui,but some how the void tear always comes into play

rarmor: 1.11.2-r4.2
reliquary:1.11.2-1.3.3.635
forge:1.11.2-2227
crash report:
[crash-2017-02-08_23.49.41-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/760627/crash-2017-02-08_23.49.41-server.txt)

**Comment by SDUBZ** [comment] 2017-02-08 13:00
i would also like @canitzp  to join this issue so we can all try to figure this out and why its making clients crash from 2 different mods

**Comment by canitzp** [comment] 2017-02-08 13:08
I fixed the NoClassDef error on my side. I think that reliquary tried to get a capability that isn't forge units from one of the rarmor items and this crashed it

**Comment by SDUBZ** [comment] 2017-02-08 13:15
actually oddly enough i added tesla api from curseforge and it fixed it and havent crashed so far

**Comment by canitzp** [comment] 2017-02-08 13:19
4.2 was a fix for this error and it isn't away?

**Comment by SDUBZ** [comment] 2017-02-08 13:21
no it still crashed without tesla api after awhile

**Comment by SDUBZ** [comment] 2017-02-08 13:22
also your modules are derping from time to time say i have solar and generator together half the time they fight against each other

**Comment by P3pp3rF1y** [comment] 2017-02-08 13:41
@canitzp Reliquary just runs stack.hasCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null). The issue is really the call to getCapability in that part of code instead of actually checking if the capability passed in is in the list of capabilities supported by the item.

**Comment by canitzp** [comment] 2017-02-08 15:29
I'll take a look into it later today. hasCapa simple checks getCapa != null cause I'm lazy

**Comment by canitzp** [comment] 2017-02-08 16:14
okay I'm a idiot, I forgot braces and so the if doesn't work properly. I push 4.3 in a hour

**Comment by canitzp** [comment] 2017-02-08 16:31
@SDUBZ I fixed it finally in 4.3, upload in some minutes. For the module derping, please open a issue at my repo and I fix it, cause I tried it and for me they work just fine

**Comment by canitzp** [comment] 2017-02-08 16:51
https://github.com/canitzp/Rarmor/commit/73d46643aac057605f488ccdac035e2e22899c0a

**Closed as completed** 2017-02-11 09:45 UTC
